import os
import sys
import glob
import subprocess
import argparse
import xml.etree.ElementTree as ET

 
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SIM_TIME = 100 #seconds
# get_just_the_directory(get_absolute_path())
# "/home/tassany/sumo/generate.py" -> "/home/tassany/sumo"


def clean_output_dir(output_dir: str):
    """Delete generated simulation files from a previous run."""
    # List of file patterns generated by the simulation (* is a wildcard)
    patterns = ["*.net.xml", "*.rou.xml", "*.trips.xml", "*.sumocfg", "*.xml", "*.tcl"]
    # List that will accumulate the names of deleted files
    deleted = []
    # Iterate over each pattern (e.g. "*.xml", "*.tcl", ...)
    for pattern in patterns:
        # glob.glob finds all files in the directory matching the pattern
        # os.path.join combines output_dir with the pattern: e.g. "/home/tassany/sumo/*.xml"
        for f in glob.glob(os.path.join(output_dir, pattern)):
            os.remove(f)                          # delete the file
            deleted.append(os.path.basename(f))  # keep only the filename (without the path)
    if deleted:
        # ', '.join(deleted) joins the names into a comma-separated string
        # e.g. ["a.xml", "b.tcl"] -> "a.xml, b.tcl"
        print(f"  Deleted {len(deleted)} file(s): {', '.join(deleted)}")
    else:
        print("  No files to delete.")


def generate_network(output_dir: str):

    network_file = os.path.join(output_dir, "map.net.xml")
    if os.path.exists(network_file):
        print(f" Network already exists: {network_file}")
        return network_file
    
    cmd = ["netconvert",
           "--node-files", os.path.join(output_dir, "map.nod.xml"),
           "--edge-files", os.path.join(output_dir, "map.edg.xml"),
           "--output-file", network_file]
    subprocess.run(cmd, check=True)

    return network_file



def generate_sumo_config(output_dir: str, network_file: str, routes_file: str):

    fcd_file = os.path.join(output_dir, "fcd.xml")
    config_file = os.path.join(output_dir,"sim.sumocfg")


    root = ET.Element("configuration")
    input = ET.SubElement(root, "input")
    ET.SubElement(input, "net-file", attrib={"value": os.path.basename(network_file)})
    ET.SubElement(input, "route-files", attrib={"value": os.path.basename(routes_file)})

    time = ET.SubElement(root, "time")
    ET.SubElement(time, "begin", attrib={"value": "0"})
    ET.SubElement(time, "end", attrib={"value": str(SIM_TIME)})
    ET.SubElement(time, "step-length", attrib={"value": "0.1"})

    out = ET.SubElement(root, "output")
    ET.SubElement(out, "fcd-output", attrib={"value": os.path.basename(fcd_file)})
    
    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    tree.write(config_file, xml_declaration=True, encoding="unicode")
    
    return config_file, fcd_file

def run_sumo(output_dir: str, cfg_file: str):
    fcd_file = os.path.join(output_dir, "fcd.xml")
    cmd = ["sumo", "-c", cfg_file, "--no-warnings", "--no-step-log"]
    subprocess.run(cmd, check=True)
    return fcd_file

def convert_to_ns3(output_dir: str, fcd_file: str):
    sumo_home = os.getenv("SUMO_HOME")
    exporter_py = os.path.join(sumo_home, "tools", "traceExporter.py")
    ns3_file = os.path.join(output_dir, f"mobility.tcl")

    cmd = [
        "python3", exporter_py,
        "--fcd-input", fcd_file,
        "--ns2mobility-output", ns3_file]
    subprocess.run(cmd)

    return ns3_file

def main():
    node_file = "map.nod.xml"
    edge_file = "map.edg.xml"
    routes_file = "veh.rou.xml"
    config_file = "sim.sumocfg"

    parser = argparse.ArgumentParser(description="Generate SUMO scenarios and convert to NS-3 format.")
    parser.add_argument("--output-dir", default=SCRIPT_DIR, help="Directory to save generated files")
    parser.add_argument("--clean", action="store_true", help="Delete previously generated simulation files before running")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # If --clean was passed, delete old files before generating new ones
    if args.clean:
        print("Cleaning output directory...")
        clean_output_dir(args.output_dir)

    print("Output directory:", args.output_dir)

    print("Generating network...")
    network_file = generate_network(args.output_dir)

    print("Generating SUMO configuration...")
    config_file, fcd_file = generate_sumo_config(args.output_dir, network_file, routes_file)

    print("Executing SUMO simulation...")
    run_sumo(args.output_dir, config_file)

    print("Converting to NS-3 format...")
    ns3_file = convert_to_ns3(args.output_dir, fcd_file)
    print(f"NS-3 mobility trace generated: {ns3_file}")



if __name__ == "__main__":
    main()