import os
import sys
import glob
import subprocess
import argparse
import xml.etree.ElementTree as ET

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# get_just_the_directory(get_absolute_path())
# "/home/tassany/sumo/generate.py" -> "/home/tassany/sumo"
SIM_TIME = 45 #seconds
AREA_SIZE = 500 #meters
GRID_CELLS = 2 #number of edges in one direction
CELL_SIZE  = AREA_SIZE // GRID_CELLS # 500m / 2 = 250m
VEHICLES = 5 #number of vehicles in the scenario


def get_sumo_home():
    sumo_home = os.environ.get("SUMO_HOME", "")
    if not sumo_home or not os.path.isdir(sumo_home):
        for candidate in ["/usr/share/sumo", "/opt/sumo"]:
            if os.path.isdir(candidate):
                return candidate
        print("ERRO: SUMO_HOME not found. Execute 'source ~/.bashrc'.")
        sys.exit(1)
    return sumo_home


def clean_output_dir(output_dir: str):
    """Delete generated simulation files from a previous run."""
    # List of file patterns generated by the simulation (* is a wildcard)
    patterns = ["*.net.xml", "*.rou.xml", "*.trips.xml", "*.sumocfg", "*.xml", "*.tcl"]
    # List that will accumulate the names of deleted files
    deleted = []
    # Iterate over each pattern (e.g. "*.xml", "*.tcl", ...)
    for pattern in patterns:
        # glob.glob finds all files in the directory matching the pattern
        # os.path.join combines output_dir with the pattern: e.g. "/home/tassany/sumo/*.xml"
        for f in glob.glob(os.path.join(output_dir, pattern)):
            os.remove(f)                          # delete the file
            deleted.append(os.path.basename(f))  # keep only the filename (without the path)
    if deleted:
        # ', '.join(deleted) joins the names into a comma-separated string
        # e.g. ["a.xml", "b.tcl"] -> "a.xml, b.tcl"
        print(f"  Deleted {len(deleted)} file(s): {', '.join(deleted)}")
    else:
        print("  No files to delete.")


def generate_network(output_dir: str):
    network_file = os.path.join(output_dir, "grid.net.xml")
    if  os.path.exists(network_file):
        print(f"    The network file already exists: {network_file}")
        return network_file
    cmd = [
        "netgenerate",
        "--grid",
        f"--grid.number={GRID_CELLS + 1}",
        f"--grid.x-length={CELL_SIZE}",
        f"--grid.y-length={CELL_SIZE}",
        "--grid.attach-length=0",
        "--default.speed=30",                 # maxSpeed = 30 m/s
        # f"--offset.x={AREA_SIZE // 2}",
        # f"--offset.y={AREA_SIZE // 2}",
        "--output-file", network_file,
    ]
    subprocess.run(cmd, check=True)
    return network_file

def generate_routes(output_dir: str, net_file: str, num_vehicles: int):
    sumo_home  = get_sumo_home()
    rtrips_py  = os.path.join(sumo_home, "tools", "randomTrips.py")

    routes_file  = os.path.join(output_dir, f"routes.rou.xml")

    if os.path.exists(routes_file):
        print(f"  Routes already exist: {routes_file}")
        return routes_file
    

    # The randomTrips.py script generates trips at regular intervals. 
    # To insert a total of `num_vehicles` vehicles, we can calculate the insertion end time based on a fixed period. 
    # For example, if we choose a period of 0.1 seconds, the insertion end time would be `num_vehicles * period`.
    # IN 3.0s we would have 30 vehicles, which is a reasonable rate for our scenario.
    period = 0.1
    insertion_end = num_vehicles * period

    cmd = [
        "python3", rtrips_py,
        "-n", net_file,
        "-b", "0",
        "-e", f"{insertion_end:.1f}",
        "-p", f"{period:.1f}",
        "--trip-attributes", 'type="car"', 
        "--fringe-factor", "1",          
        "--min-distance", "500",         
        "--allow-roundabouts",
        "--route-file", routes_file,
    ]
    subprocess.run(cmd, check=True)
    return routes_file

def generate_vehicle_type(output_dir: str):
    vtypes_file = os.path.join(output_dir, "vtypes.add.xml")
    root = ET.Element("additional")
    vtype = ET.SubElement(root, "vType")
    vtype.set("id",       "car")
    vtype.set("accel",    "2.0")     
    vtype.set("decel",    "2.0")     
    vtype.set("maxSpeed", "30.0")    
    vtype.set("length",   "4.5")     
    vtype.set("width",    "2.0")
    vtype.set("sigma",    "0.0")
    vtype.set("color",    "1,0,0")

    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    tree.write(vtypes_file, xml_declaration=True, encoding="unicode")
    
    return vtypes_file


def generate_sumo_config(output_dir: str, net_file: str,
                         routes_file: str, vtypes_file: str,
                         num_vehicles: int):
    
    #Floating car data??? 
    fcd_file = os.path.join(output_dir, f"fcd.xml")
    config_file = os.path.join(output_dir, f"scenario.sumocfg")

    if os.path.exists(config_file) and os.path.exists(fcd_file):
        print(f"  Config already exists: {config_file}")
        return config_file, fcd_file
    
    root = ET.Element("configuration")
    inp = ET.SubElement(root, "input")
    ET.SubElement(inp, "net-file",        attrib={"value": os.path.basename(net_file)})
    ET.SubElement(inp, "route-files",     attrib={"value": os.path.basename(routes_file)})
    ET.SubElement(inp, "additional-files",attrib={"value": os.path.basename(vtypes_file)})

    time = ET.SubElement(root, "time")
    ET.SubElement(time, "begin", attrib={"value": "0"})
    ET.SubElement(time, "end",   attrib={"value": str(SIM_TIME)})
    ET.SubElement(time, "step-length", attrib={"value": "0.1"})

    out = ET.SubElement(root, "output")
    # Save the Floating Car Data (FCD) for post-simulation analysis
    ET.SubElement(out, "fcd-output", attrib={"value": os.path.basename(fcd_file)})

    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    tree.write(config_file, xml_declaration=True, encoding="unicode")
    return config_file, fcd_file

def run_sumo(output_dir: str, cfg_file: str):
    fcd_file = os.path.join(output_dir, "fcd.xml")
    cmd = ["sumo", "-c", cfg_file, "--no-warnings", "--no-step-log"]
    subprocess.run(cmd, check=True)
    return fcd_file

def convert_to_ns3(output_dir: str, fcd_file: str):
    sumo_home = os.getenv("SUMO_HOME")
    exporter_py = os.path.join(sumo_home, "tools", "traceExporter.py")
    ns3_file = os.path.join(output_dir, f"mobility.tcl")

    cmd = [
        "python3", exporter_py,
        "--fcd-input", fcd_file,
        "--ns2mobility-output", ns3_file]
    subprocess.run(cmd)

    return ns3_file

def main():
    parser = argparse.ArgumentParser(description="Generate SUMO scenarios and convert to NS-3 format.")
    parser.add_argument("--output-dir", default=SCRIPT_DIR, help="Directory to save generated files")
    parser.add_argument("--clean", action="store_true", help="Delete previously generated simulation files before running")
    parser.add_argument("--vehicles", type=int, default=VEHICLES, help="Number of vehicles in the scenario")

    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # If --clean was passed, delete old files before generating new ones
    if args.clean:
        print("Cleaning output directory...")
        clean_output_dir(args.output_dir)

    print("Output directory:", args.output_dir)

    print("Generating network...")
    network_file = generate_network(args.output_dir)

    print("Generating vehicle types...")
    vtypes_file = generate_vehicle_type(args.output_dir)

    print("Generating routes...")
    routes_file = generate_routes(args.output_dir, network_file, args.vehicles)
    
    print("Generating SUMO configuration...")
    cfg_file, fcd_file = generate_sumo_config(args.output_dir, network_file, routes_file, vtypes_file, args.vehicles)
    
    print("Executing SUMO simulation...")
    run_sumo(args.output_dir, cfg_file)

    print("Converting to NS-3 format...")
    ns3_file = convert_to_ns3(args.output_dir, fcd_file)
    print(f"NS-3 mobility trace generated: {ns3_file}")



if __name__ == "__main__":
    main()